services:
  backend:
    image: zymbsis/messenger-app-backend:latest
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/messenger
    depends_on:
      - db

  frontend:
    image: zymbsis/messenger-app-frontend:latest
    ports:
      - '5173:5173'
    depends_on:
      - backend

  db:
    image: postgres:17.6-bookworm
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=messenger
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres_data:
