services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
    working_dir: /app
    command: pipenv run fastapi run main.py --host 0.0.0.0 --port 8000
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/dbname
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 5173
    depends_on:
      - backend

  db:
    image: postgres:17.6-bookworm
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
